Refactor create general order code
hmcts/finrem-case-orchestration-service pull request #1524
Opened 2024-01-25 14:22 UTC by jthmcts

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/DFR-2646

### Change description ###
Refactor create general order callback code to use handlers

2024-01-26 14:29 UTC, rishikrsharma commented on src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/creategeneralorder/CreateGeneralOrderAboutToStartHandler.java
> +            return false;
Please move them into separate handlers. One for Contested and one for Consented.

2024-01-26 14:30 UTC, rishikrsharma commented on src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/creategeneralorder/CreateGeneralOrderAboutToSubmitHandler.java
> +            return false;
same - move to separate handler

2024-01-26 14:32 UTC, rishikrsharma commented on src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderService.java
> +        GeneralOrder generalOrder = new GeneralOrder();
may be use builder here

2024-01-26 14:35 UTC, rishikrsharma commented on src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderService.java
> +            if (generalOrderWrapper.getGeneralOrders() == null) {
Optional.OfNullable will be better

2024-01-26 15:00 UTC, gmikerlemos requested changes
Overall ok but the handler must be split and the static method in FinremCaseDetails seems to be misplaced.

2024-01-29 09:32 UTC, jthmcts commented on src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/creategeneralorder/CreateGeneralOrderAboutToSubmitHandler.java
> +            return false;
Done

2024-01-29 09:32 UTC, jthmcts commented on src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderService.java
> +        GeneralOrder generalOrder = new GeneralOrder();
Done

2024-01-29 09:32 UTC, jthmcts commented on src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/creategeneralorder/CreateGeneralOrderAboutToSubmitHandler.java
> +        if (isContestedCase(caseDetails)) {
Code has been removed

2024-01-29 09:33 UTC, jthmcts commented on src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/FinremCallbackRequest.java
> +    public static FinremCallbackRequest from(FinremCaseData caseData) {
Removed

2024-01-29 09:34 UTC, jthmcts commented on src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderServiceTest.java
> +    public void testAddContestedGeneralOrderInCollection_ConsentedInContested() throws Exception {
Refactoring has meant this method has now changed

2024-01-29 09:35 UTC, jthmcts commented on src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/creategeneralorder/CreateGeneralOrderAboutToSubmitHandler.java
> +    private boolean isContestedCase(FinremCaseDetails caseDetails) {
Code has been removed

2024-01-29 10:55 UTC, jthmcts commented on src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderService.java
> +            if (generalOrderWrapper.getGeneralOrders() == null) {
Done

2024-01-29 10:55 UTC, jthmcts commented on src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderService.java
> +        if (generalOrderWrapper.getGeneralOrderCollection() == null) {
Done

2024-01-29 10:55 UTC, jthmcts commented on src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/correspondence/FinremEmailOnlyAllSolicitorsCorresponder.java
> +    protected boolean shouldSendIntervenerSolicitorEmail(FinremCaseDetails caseDetails,
Done

2024-01-30 08:03 UTC, merged