FR-1551: Respondent solicitor email for FR contested application issued
hmcts/finrem-case-orchestration-service pull request #493
Opened 2020-11-04 12:04 UTC by jakub-kozlowski

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/FR-1551

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2020-11-04 12:47 UTC, johnoneill46 approved these changes

2020-11-04 13:47 UTC, ocarleton approved these changes

2020-11-04 13:49 UTC, shaunganley reviewed
looks good, couple of small comments

2020-11-04 13:49 UTC, shaunganley commented on src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsControllerTest.java
> +        mockMvc.perform(post(CONTESTED_APPLICATION_ISSUED_CALLBACK_URL)
have a look at my PR, we should be calling the method directly for unit tests rather than over HTTP

2020-11-04 13:49 UTC, shaunganley commented on src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsControllerTest.java
> +        verify(notificationService, times(0)).sendContestedApplicationIssuedEmailToRespondentSolicitor(any());
use never() instead of times(0)

2020-11-04 16:21 UTC, shaunganley requested changes
have a look at my PR, we should be calling the method directly for unit tests rather than over HTTP

2020-11-06 16:43 UTC, shaunganley approved these changes

2020-11-06 17:04 UTC, merged