Dfr 891
hmcts/finrem-case-orchestration-service pull request #660
Opened 2022-04-26 15:14 UTC by EllisD-B

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/DFR-891

### Change description ###

Notice of change add and replace functionality for solicitor (new PR as builds were getting stuck on Jenkins at deploy stage)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-04-26 16:35 UTC, gmikerlemos requested changes

2022-04-26 16:38 UTC, gmikerlemos commented on src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/UpdateSolicitorDetailsService.java
> +            caseData.put(isConsented ? CONSENTED_SOLICITOR_NAME : CONTESTED_SOLICITOR_NAME,
should extract this section as well as the Respondent section was extracted to keep it concise

2022-04-26 16:45 UTC, gmikerlemos commented on src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/UpdateRepresentationService.java
> +            .party(isApplicant ? "Applicant" : "Respondent")
Can you add these to a public constants class?

2022-04-27 15:29 UTC, rishikrsharma approved these changes

2022-04-28 13:05 UTC, gmikerlemos commented on src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/ChangeOfRepresentation.java
> +public class ChangeOfRepresentation {
This class must be renamed to avoid confusion with ChangeOfRepresentatives

2022-05-03 10:20 UTC, gmikerlemos commented on src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/ChangeOfRepresentationRequest.java
> +public class ChangeOfRepresentationRequest {
Should avoid using prepositions in classes names

2022-05-03 10:20 UTC, gmikerlemos commented on src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/RepresentationUpdateHistory.java
> +public class RepresentationUpdateHistory {
This class seems to be unnecessary, your choice, either refactor or create a techdebt and assign yourself to it due to time constraints

2022-05-11 07:39 UTC, ruban72 approved these changes

2022-05-18 07:45 UTC, closed without merging